package me.randomhashtags.randomsky.util;

public enum Feature {
    ADVENTURE,
    ADVENTURE_MAP,
    ADVENTURE_MAP_FRAGMENT,

    ALLIANCE_RELATION,
    ALLIANCE_RELATIONSHIP,
    ALLIANCE_ROLE,
    ALLIANCE_UPGRADE,

    AUTO_BOT,
    AUTO_BOT_UPGRADE,

    COLLECTION_CHEST,
    COLOR_CRYSTAL,

    CUSTOM_ENCHANT,
    CUSTOM_ENCHANT_RARITY,
    CUSTOM_KIT,
    CUSTOM_RECIPE_ITEM,

    EVENT_ATTRIBUTE,
    EVENT_CONDITION,

    FARMING_LIMIT_INCREASE,
    FARMING_RECIPE,
    FILTER_CATEGORY,
    LOOTBOX,
    LUCKY_BLOCK,
    MYSTERY_GEM,

    INVENTORY_PET,

    ITEM_RECIPE,

    PLAYER_RANK,
    PLAYER_SKILL,
    PLAYER_SKILL_LEVEL,

    RARITY_SECRET_DUST,
    REPAIR_SCROLL,

    REALM,

    RESOURCE_FRAGMENT,
    RESOURCE_ITEM,
    RESOURCE_NODE,
    RESOURCE_REFINED,
    RESOURCE_SCRAP,
    RESOURCE_UNREFINED,

    SCRAP,

    SHOP_CATEGORY,

    TEAM,

    TELEPORT_PAD,
    TELEPORT_PAD_SETTINGS,

    ISLAND_CHALLENGE,
    ISLAND_LEVEL,
    ISLAND_ORIGIN,
    ISLAND_PERMISSION_BLOCK,
    ISLAND_PROGRESSIVE_SKILL,
    ISLAND_RANK,
    ISLAND_REGION_PROTECTION,
    ISLAND_SKILL,
    ISLAND_UPGRADE,
}
